# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 23:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_order_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completion_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
