# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180602_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=200)),
                ('cloth_rate', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='blog.Order')),
            ],
        ),
    ]
