# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_ratelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='clothing',
            field=models.TextField(),
        ),
    ]
